### ISSUE TITLE
Development: Multiple API calling on Topic creation

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1544]
As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/0e889389-05a5-4c12-90d5-fe6b6d19df19)

**Comment by DevAlchemyCD** [comment]
@hassaanCD ! I have verified it on development. It is working fine there. The breadcrumb API is called twice because at once we are loading the data for both the side drawer and topic detail page simultaneously.

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/99801525/3c184ffb-b3b6-4346-9bed-8a29d9246832)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by hassaanCD** [comment]
Not fixed on production


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/982a1f81-2ed4-4fbe-9c4c-e3d39914ba49)

**Comment by DevAlchemyCD** [comment]
@hassaanCD ! breadcrumb is called two times because we are calling It for every change regarding URL and filters. When we land on topic detail page we call breadcrumb API and then drawer is opened due to which the URL is updated and breadcrumb API is called again for the content of drawer.

**Comment by hassaanCD** [comment]
Working fine on production
