### ISSUE TITLE
Disable Sign button for delegate supporters on topic detail page

### ISSUE THREAD

**Issue by DevAlchemyCD** [the-canonizer/canonizer-3.0-frontend#1715]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/99801525/95c7cd08-366e-493f-b6e7-a9cb4dfcf0d8)

**Comment by DevAlchemyCD** [comment]
Commit : https://github.com/the-canonizer/canonizer-3.0-frontend/commit/92c580ea7251e9d5a646b4d3979c0b406f09b5ce

**Comment by sajid315** [comment]
> Commit : [92c580e](https://github.com/the-canonizer/canonizer-3.0-frontend/commit/92c580ea7251e9d5a646b4d3979c0b406f09b5ce)

This is working fine but we need to update the message of disabled button because the reason is : User already signed this camp.
So i think message should be like "You've already signed to the camp leader". Please update.

**Comment by DevAlchemyCD** [comment]
@sajid315 ! The message (on the sign button popup) for direct supporters and delegate supporters has been updated now.

**Comment by saniatg** [comment]
@wahaj-hafeez the message is incorrect
![Screenshot 2024-05-23 at 11 31 15 AM](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/91254708/51960cca-ae52-4011-bf7f-1e0320dc94ce)

**Comment by sajid315** [comment]
@saniatg , 
This ticket is already working , the actual scenario is as follows:

1. When user signs a camp , he actually delegating the camp leader.
2. And when user delegates his support to a user using "Delegate your support" , it behaves same.

So in case user delegates using above point 2 then he should not be able to click on sign button. Because he already have delegation in this camp. And Sign button should be disabled as in following screenshot, 

![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/cc18bf58-651e-43d4-8418-7bf4cf298417)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
