### ISSUE TITLE
Current Camp Recent Activities" are showing after page refresh

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer-3.0-frontend#1813]
Steps to Reproduce:
Login and create a topic
Create a camp
Add and Remove support
Observe "Current Camp Recent Activities" section
It only show recent activities after page refresh

**Comment by DevAlchemyCD** [comment]
PR:https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1768

**Comment by saniatg** [comment]
@wahaj-hafeez removed support is not showing in recent camp activities , on refresh is it working.

**Comment by DevAlchemyCD** [comment]
@sajid315 when we perform any add and remove activity the latest data does not come from the API. After page refresh the latest data has come and is displayed in the recent activity

**Comment by sajid315** [comment]
I have looked into this issue, so the actual reason for this issue is Queue Jobs for activity, when the user requests the fresh activities it depends on base of job execution.
So we need to update that logic according to requirement, either we have to go with direct MySQL approach OR some real time sockets can be helpful.

**Comment by sajid315** [comment]
As discussed in the last week meeting with Ali & Sunny , we don't need to change the architecture. Even we have to call API after sometime on front-end side. 
So in UI/UX we will handle this accordingly.

**Comment by rupalichavan9860** [comment]
I discussed this with @sajid315 , and it is currently on hold, so I'm transferring this to In Progress for now.
