### ISSUE TITLE
Wrong canon name is showing in "camp statement history" & "camp history page"

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1991]
it is showing "General" instead of "Sandbox"

![Image](https://github.com/user-attachments/assets/7832d1aa-a28d-4ad5-9fe9-472719783baf)

**Comment by sajid315** [comment]
@akashgit77 this is not an issue , because the older design were having the "Canon" in bread crumb. That is removed now. 

Also I just verified that the canon is coming correct for topic and camp history record. Also the canon name is correct in the breadcrumb tool tip.

You can have a look and then we can move this ticket ahead.

**Comment by rupalichavan9860** [comment]
Yes @sajid315 Canon from bread crumbs is removed now so closing this
