### ISSUE TITLE
URL reload and multi API calls issue

### ISSUE THREAD

**Issue by DevAlchemyCD** [the-canonizer/canonizer-3.0-frontend#2206]
As discussed on call with @ks-rahul , we are having the issue with URL reload (specifically in the case of the videos page). Also on some of the pages the "useEffect" is triggering multiple times. So in a recent investigation and code review, we found the issue in the wrapper of the application that is about the redirection of users to the same pages after authentication, where they are doing some actions.

we need to fix this issue and need to recheck the flow of:-
1- Videos player page
2- History pages
3- Breadcrumb calls etc  ...

**Comment by sajid315** [comment]
@rupalichavan9860 
This ticket was made due to reload issue on videos page while clicking on any video in the playlist.

The problem was, complete page was reloading on each video play. Now that issue is fixed and page is loading only one time even user navigates b/w the playlist of videos.

It's working and we can move this ticket ahead then.
