### ISSUE TITLE
Need ability to change I "agree" with a change, until change goes live.

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#857]
![Image](https://user-images.githubusercontent.com/6559312/223245557-a70dde3a-c99f-46b8-8b45-2df7ba3434ab.png)

Supporters can "agree" to a proposed change, as indicated in the above image.
Once all supporters say they agree, the change should go live.
But until that time, people that have indicated they agree, should have the ability to change their mind, and remove their agreement.

**Comment by array-junkie** [comment]
@BrentAllsop, @rupalichavan9860 

Yes, we can do it, but there are some different scenarios needs discussion. 
If we go by an example as below.
1- Currently if there are (e.g : 10 supporters either direct or implicit) and 9 of them agreed to the change and 01 still have to agree within 24 hours. At that time if anyone from already 09 supporters remove the agreement. 
So for this action they only have to un-check the agreement box ? 

What will be the effect on change if somebody will (disagree or remove agreement) after agreed once ?

**Comment by BrentAllsop** [comment]
Let's also add andicator 'R' of how many supporters are required to agree for it to go live.
And a number 'A' who have selected the Agree checkbox.
This will result in report something like this:
"A out of R required supporters have agreed."
If A = 9, and R = 10, then the one person who has not yet agreed, can then know once they agree, all 10 of 10 will agree and it will go live / turn green.
If you are the last hold out (i.e. you are the 10th (or last) of 9 supporters already agreeing), it would be nice to also add the additional statement: "Since you are the last hold out, the instant you agree, this will go live."

**Comment by sajid315** [comment]
PR Raised
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/869

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
